### ISSUE TITLE
Discrepancy between "cutoff" and "quantile" in plotting results for heatmap and circos plot.

### ISSUE THREAD

**Issue by iUser1234** [saeyslab/nichenetr#103]
Hi,

I have stumbled upon an issue which I cannot seem to wrap my head around. I've followed your vignette for how to apply NicheNet on a Seurat Object as well as the vignette for how to plot a circos plot. Both of them worked without issues. However, when I closely compare the output of the "Ligand --> Predicted Target" heatmap and the circos plot which should illustrate the same thing, I noticed that some genes that appear in the heatmap aren't found in the circosplot, leading me to believe that the "quantile" variable used for filtering out genes prior to making the circos plot somehow is more stringent, even though the function in which the "cutoff" variable is found explicitly states "Quantile cutoff on the ligand-target scores of the input weighted ligand-target network. Scores under this cutoff will be set to 0." which should thus be exactly the same? I have set both of them to 0.4. 

What makes this even more strange is that when I check the actual weights for some of the genes that are excluded in the circos plot, they are clearly higher than the cutoff value. I think the reason for that, which also compounds the strangeness of the issue, is that the information stored in the "active_ligand_target_links_df" dataframe doesn't exactly match what is then plotted, for reasons that I have yet to figure out yet. For instance, when I check one of the genes, Satb1, I get these two outputs: 

`active_ligand_target_links_df[active_ligand_target_links_df$target == 'Satb1',]`
`# A tibble: 1 x 5`
`ligand target   weight target_type ligand_type`
  `<chr>  <chr>     <dbl> <chr>       <chr> `    
`1 Lrrc4c Satb1  0.000950 2           2`

`active_ligand_target_links['Satb1',]`
    `Celsr2       Ncam1       Robo1       Dscam      Cx3cl1       Ptprt      Pcdh15        Nrg1      Lrrc4c        Cdh6 
0.000000000 0.000000000 0.000000000 0.001921928 0.001284596 0.001494030 0.001279546 0.000000000 0.000000000 0.001738607 `

In my case, the 40% cutoff value returns 0.00106817, so it makes sense why this gene would be excluded from the circos plot, but what is driving the discrepancy in the dataframe and matrix? Just as the vignette says, I use this to generate the latter matrix in the first place:

`active_ligand_target_links = prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df ligand_target_matrix = ligand_target_matrix, cutoff = .4)`

So in the dataframe, Lrrc4c has a weighted value for Satb1 of 0.0009 while no other ligands have Satb1 as the target, but this is then completely different in the matrix in which we have multiple other ligands with weights for Satb1, but not Lrrc4c?

Thanks in advance!

**Comment by browaeysrobin** [comment]
Hi @iUser1234 

Thank you for raising this issue, and checking everything so thoroughly!

I see two sides on this: 

1. the discrepancy between the data frame `active_ligand_target_links_df` and the matrix `active_ligand_target_links`, and 
2. the discrepancy between which of the two is used in the ligand-target heatmap visualizations vs circos visualizations

About the first point: This has to do with the 2-step procedure in which the ligand-target links are inferred (which is unfortunately not elegant). First, `active_ligand_target_links_df` is built, and shows only the ligand-target links for which the target gene belongs to the top _n_ targets of that ligand. In your case, only for the ligand Lrrc4c, Satb1 is in the top _n_. 
Secondly, we use the information from `active_ligand_target_links_df` to make `active_ligand_target_links`. This is done by taking all ligands, and all targets in  `active_ligand_target_links_df`, and get the regulatory potential scores for all the links between each ligand-target combination (= just taking the subset of the prior ligand_target_matrix). In your case, this means that we will look for the regulatory potential scores between Satb1 and the ligands Celsr2 Ncam1 Robo1 Dscam Cx3cl1 Ptprt Pcdh15 Nrg1 Lrrc4c Cdh6. Then we set every score below the cutoff to zero. In this case, this will make the Lrrc4c-Satb1 link disappear, although it was the only link found in the  `active_ligand_target_links_df`. 
The reason Lrrc4c-Satb1 was the only one in the dataframe is thus because Satb1 is not a top _n_ target of one of the other ligands, but only of Lrr4c (more 'relative' evidence for Lrr4c). But apparently, the other ligands have higher regulatory potential scores - meaning there is more absolute evidence supporting their link to Satb1. 

About the second point: the cutoff to make the circos plot is now made on the `active_ligand_target_links_df` data frame, and not on the  `active_ligand_target_links` as for the heatmap visualization  - this will lead to different cutoffs used and thus different links visualized. There is however no reason to do this differently, so thank you for pointing this out. I will be on holidays from tomorrow on, but afterwards I will fix this in the circos vignettes.

**Comment by iUser1234** [comment]
Hi,

Thanks for your very quick reply! So in essence, if I'm understanding you correctly, what you're saying is that when it comes to the heatmap, the dataframe is "just" used to identify every ligand and target to be included, and that the potential is in essence re-checked for every ligand-target combination? Does that mean that if I would lower the top _n_ when generating the dataframe such that Satb1 does nto appear for Lrrc4c, it wouldn't appear at all in the heatmap?

**Comment by browaeysrobin** [comment]
Hi @iUser1234 

You are 100% correct!

**Comment by iUser1234** [comment]
I see. I fixed it by making the circos tibble directly from the ``active_ligand_target_links``matrix to ensure that they look exactly identical. As far as I can tell, there shouldn't be an issue by doing it this way. I'll close this now but if you disagree, please let me know. Thanks for your help.
