### ISSUE TITLE
Subset causes loss of data of other columns

### ISSUE THREAD

**Issue by zedzedwhy** [saeyslab/nichenetr#111]
Hi, 
When I performed "subset" on my seurat object (I've made sure that receiver exists):
`seurat_obj_receiver= subset(seurat.object, idents = receiver) `
and then I looked at my column "Tissue": 
`seurat_obj_receiver$Tissue`
This data becomes <NA> in all the cells, which is not the case in the example. 
The error when running `nichenet_seuratobj_aggregate` is: 
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: T

**Comment by zedzedwhy** [comment]
becomes "NA" in all the cells, sorry.

**Comment by browaeysrobin** [comment]
Hi @zedzedwhy 

What exactly is the `receiver` vector you give as argument for `idents`?
Also notice that this is likely a Seurat issue - question and not a NicheNet one

**Comment by zedzedwhy** [comment]
Hi @browaeysrobin 
The receiver is "CD4 T" in the $Global_Cluster of the object. Oh yes it seems to be exactly a Seurat issue. 
Thanks anyway!

**Comment by browaeysrobin** [comment]
Hi @zedzedwhy 

You are using the `subset` function of Seurat incorrectly in that way. 
`idents` argument requires a vector of cell identity names that you want to subset
if you want only cells that are CD4 T cells, you should do something similar like: subset(seurat.object, subset = Global_Cluster == "CD4 T)

Please have a look at the help page and manual of Seurat, and ask a question to their developers if something would still not be clear about this function.

I will close the issue because it seems a Seurat question
