### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nanoonc** [saeyslab/nichenetr#115]
Hello, 

I am wondering if there is a way to feed proteomic and RNAseq datasets into nichenet to predict receptor-ligand interactions, or is the package limited to just RNAseq data?

**Comment by browaeysrobin** [comment]
Hi @nanoonc 

It is possible to use proteomics data as input data for a NicheNet analysis. There is no pre-made vignette about using NicheNet on proteomics though, so you will need to follow the steps described in the current vignettes, and adapt the code to proteomics instead of transcriptomics data (will boil down to write the code yourself to go from proteomics data to expressed ligands, expressed receptors and geneset of interest (differential proteins)).
