### ISSUE TITLE
how to set best the gene set of interest 

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#116]
Hi dear nichenetr Teams,

Thank you for the tool and I am using it pretty often but confused about defining the gene set of interest. 

I used all differently expressed genes as a set of genes of interest, and the AUROC value of the prioritized ligands was below 0.6.  If I am correct, this means NicheNet does not find the target gene expression on the receiver cell.
As an option, I  did GSEA for all differently expressed genes and, then I used the gene sets in the enriched pathways as my gene set of interest and surprisingly, I got better prediction value (AUROC >0.6)

Would please explain to me why this could happen?

Thank you!

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

For the GSEA analysis, did you use the overlap between your DE genes and the geneset of GSEA? or did you use the entire geneset of GSEA? I would not do the latter. 
A better prediction in the case of GSEA-based geneset is probably because these genes all belong to the same pathway, are well studied, are regulated in a similar way, and are thus easier to predict as downstream targets for ligands in the NicheNet framework

**Comment by adesalegn** [comment]
Hi Robin, yes I used all the gene sets of GSEA? However, I did not check the overlap between DE genes and the gene sets from GSEA. 
Additionally, would it be okay If I consider upregulated ligands in my sender cell as the only potential ligands and only upregulated receptors in my receiver cell population as the only source of receptor? Do you think the prediction would be okay?    Thanks for answering my question.

**Comment by browaeysrobin** [comment]
*all GSEA genesets are fine -- but what I don't recommend is taking all genes from a GSEA-geneset as geneset of interest if they are not differentially expressed in your celltype of interest
* including downregulated genes can be useful because some ligands induce both upregulation and downregulation. Downregulated genes can thus also be informative in indicating which ligands might be active
* if you only consider both upregulated ligands and receptors, you might filter out some potentially interesting ligand-receptors if only ligand or receptor would be upregulated, or if higher activity of that ligand-receptor pair might be due to posttranscriptional mechanisms

Just to be sure: if you are talking about differential expression/upregulation/downregulation, you are talking about differences between two conditions and not about the marker genes of cell populations?

**Comment by adesalegn** [comment]
Thanks a lot Robin for answering my question and for the great tool.
