### ISSUE TITLE
Differential NicheNet for short time course data 

### ISSUE THREAD

**Issue by kanekalla** [saeyslab/nichenetr#123]
Thank you team for differential NicheNet.
I am trying to infer the cell-cell communication using flow sorted bulk RNA-seq data. 
Can I use differntial NicheNet approach to assess the ligand-receptor communication for short time course data (3-4 time points) across multiple cell types ? 
I appreciate your help !

**Comment by browaeysrobin** [comment]
Hi @kanekalla 

It depends on what you want to get out of the analysis (what _differences_ are you interested in etc), but in most cases yes. In terms of code, you will need to adapt many steps in the analysis to work on bulk RNAseq data instead of single-cell RNAseq data. But if the output of every step is in the same format, the final prioritization should work. 

We will not provide these code changes ourselves though, since it is too distant from the main application.  But feel free to ask further specific questions if you would try to implement this.
