### ISSUE TITLE
Differential NicheNet Plot Interpretation

### ISSUE THREAD

**Issue by ejc043** [saeyslab/nichenetr#149]
Hello Saeys team, 
Thank you for such a wonderful package. 
I have been running differential nichenet analysis and was hoping to receive some support about the output plots. I understand that ligand activity indicates enrichment of downstream genes of that ligand that are DE in receiver cells. However, what kind of transformation was done for the scaled ligand activity? And what does this indicate to us? 
Thank you so much!

**Comment by browaeysrobin** [comment]
Hi @ejc043 

The transformation applied is: z-score normalization on the ligand activity values (= pearson correlation values)
This transformation is done to compare different conditions/receiver cell types because the absolute pearson correlation values of the ligand activity are not always very comparable).
Higher values mean: there is more observed target gene enrichment for that ligands than for the majority of other ligands - making this ligand an interesting candidate to look further into.
