### ISSUE TITLE
Type of expression input drastically alters output

### ISSUE THREAD

**Issue by kpruss** [saeyslab/nichenetr#154]
I've tried running both 'old' or 'standard' NicheNet as well as Differential NicheNet with raw counts, log counts, and TPM-normalized counts in a Seurat object and the results differ (quite a bit). I was wondering what the authors recommend for the expression input? I see that "SCT" was used in the Differential NicheNet pipeline tutorial.

**Comment by browaeysrobin** [comment]
Hi @kpruss 

Thank you for raising this important issue. The chosen input will mainly be important for the DE analysis, and thus for defining the geneset of interest. Differences in the NicheNet output will likely be due to differences in the obtained geneset of interest from the DE analysis. It can possibly also affect the expressed ligands and receptors, but it think changes there will be minimal (but correct me if I'm wrong!).

We recommend to use the input that is most suited to the specific DE analysis method you use. If you use the standard Seurat FindMarkers (wilcox test, as implemented by default in the NicheNet wrapper, and given as example in the seurat_steps vignette), I recommend against using raw counts. But if you would use eg muscat (pseudobulk + edgeR), you should use the raw counts.  

Can you also elaborate on the extent by which results differ drastically? Is it the ranking within the top20/30 that changes or do you find an almost entirely different top20/30 of ligands? If the former is the case, I would not worry about this since the main interpretation of the output should be: "these top ligands have enriched target gene signatures out of 100's of potential ligands" vs "ligand with rank 3 is way more likely to be relevant than ligand with rank 6". Could you check this for the comparison you performed between Seurat logcounts and SCT? (excluding raw counts because I would not use that as input for FindMarkers)
