### ISSUE TITLE
Error when running Nichenet on spatial Seurat object

### ISSUE THREAD

**Issue by mvhunter1** [saeyslab/nichenetr#16]
Hi,

I'm trying to run Nichenet on a Seurat object composed of 10X spatial transcriptomic (not single cell) data - similar to https://satijalab.org/seurat/v3.1/spatial_vignette.html. When I try to run get_expressed_genes on my spatial Seurat object I get the following error:

Error in get_expressed_genes: trying to get slot "data" from an object of a basic class ("NULL") with no slots

My Spatial seurat object has two slots, "Spatial" and "SCT". I think the "Spatial" slot replaced the "RNA" slot that is found in single-cell Seurat objects, and this may be the reason for the error as the function is looking for data in the non-existent "RNA" slot? Any advice?

Thank you!

**Comment by browaeysrobin** [comment]
Hi @mvhunter1 

This will indeed be the reason of the error and I can and will fix this easily and quickly. 

I just have some questions concerning the direct application of NicheNet on 10x spatial transcriptomics data. In many cases, direct application won't be really appropriate I think. So, be sure it's ok to use NicheNet the way you are planning to do it. So this means: you should have changes in gene expression in receiver cells (in the spatial transcriptomics case 'spots containing multiple cells of the same of different cell types) caused by cell-cell interactions.
Feel free to ask me more questions about this if you would be in doubt.

I'll let you know when I fixed this problem.

**Comment by browaeysrobin** [comment]
Hi @mvhunter1 

If you reinstall nichenetr now, you should be able to run the `get_expressed_genes()` and seurat wrapper functions on your spatial seurat object

**Comment by mvhunter1** [comment]
HI, thank you so much for your quick reply and fix. Yes, in my spatial transcriptomic data I have data from both tumor "spots" and spots from normal tissue surrounding the tumor. I'm looking to use Nichenet to examine communication between these two cell types. Thanks again for your help!
