### ISSUE TITLE
Question for interpreting the differential nichenet results

### ISSUE THREAD

**Issue by fredust** [saeyslab/nichenetr#162]
Hello, thank you for designing the great package.
I tried the differential nichnet workflow on my data. I have some questions while interpreting the results.
I understand that the ligand should be highly expressed in the given niche, but the differential expression of the receptor means the specific receptor could be either upregulated or downregulated in the given niche, is that correct?
As I saw in the vignettes, in the top L-R pairs for "Malignant_high", some receptors were also highly expressed in the "Malignant_low" niche, such as PTPRC in the "CD2-PTPRC" pair. 
![截屏2022-08-18 09 19 32](https://user-images.githubusercontent.com/76810748/185334176-03dcaaae-bb4e-4b7c-981f-73ff540c7134.png)

Thank you very much.

**Comment by browaeysrobin** [comment]
Hi @fredust 

You should keep in mind that the ligand-receptor pairs shown are the result of a ranking/prioritization process. In this prioritization process, we calculated the logFC of the ligand, logFC of the receptor, ligand activity etc - scaled these values - and then aggregated/summed them in a weighted way (meaning some factors can be given more weight, like the logFC of the ligand in the default parameter setup). This gives a final prioritization score that is used to determine which pairs to shown on these visualizations.  

This means that it is possible that ligand-receptor pairs end up in this figure, even though not all prioritization factors get a high score. For example, a ligand-receptor pair with a strongly upregulated ligand and high ligand activity can have a slightly receptor and still end up with a high prioritization score. If you would change the parameters and give more weight to the differential expression of the receptor instead of the ligand, you might see the opposite trend.
