### ISSUE TITLE
nichenetr for bulk data for different condition 

### ISSUE THREAD

**Issue by adesalegn** [saeyslab/nichenetr#173]
Hello Robin,

I use the nichenet to understand if there is cross tissue communication for two physically closely linked tissues.  My hypothesis is since they are so close, they may have a paracrine interaction. I have three conditions, the data is bulk  a RNAseq.  I did nichenet for each condition and expected some of the top predicted ligands to be different across conditions. Would it be a good practice if I run nichenet for all samples  and try to see if the predicted ligands have expression difference between conditions? 

Best,
Amare

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

What do you mean by running NicheNet per condition? How did you define the geneset of interest? Did you use the DE genes between the condition of interest vs the 2 other conditions per tissue? Or did you do DE genes between the two tissues for each condition? I think the first approach would be better.

Checking whether predicted ligands show differential expression themselves is always a good practice indeeD.

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

The geneset of interest should be the set of genes that you think will be influenced by cell-cell communication. Let's say you take tissue 2 as sender tissue, and tissue 1 as receiver tissue. If you consider genes upregulated in tissue 1 vs tissue 2 as the geneset of interest, you assume that the specific genes of tissue 1 are induced due to cell-cell communication with tissue 2. However, this is unlikely to be true for most genes. The tissue-1-specific genes will likely arise because of different cell type composition, etc. 
This is also the reason why many of the predicted NicheNet ligands were very similar for the different conditions (the DE genes between tissues will be very similar between the different conditions).

Taking DE genes between the conditions as geneset of interest will better address the question you have. Then you assume that (part of) genes upregulated in tissue 1 in condition C vs A+B arise from communication with tissue 2. This might make more sense I think.

**Comment by adesalegn** [comment]
Hi @browaeysrobin ,

Thanks for your nice advice! I did what you recommended to me. However, just one more question: when I use all DE genes as my geneset of interest(around 700 genes), the top predicted ligand has a negative person, and AUPR values are around 0.47. When I set the gene set of interest based on the relevant enriched pathways for all DEG, I got a better person and AUPR. I am a bit confused here. What is your saying? See the attached pictures also!!

Thank you so much for being here and answering my question!!
Best,
Amare
![DEG_pathway_genes](https://user-images.githubusercontent.com/57727300/193832056-8940082a-7f50-442a-92b0-1024d79a082e.png)
![from_all_DEG](https://user-images.githubusercontent.com/57727300/193832062-e49e33d3-67d1-4b3c-9eb4-629446805450.png)

**Comment by adesalegn** [comment]
Dear Robin,

Thanks for your nice advice! I did what you recommended to me. However,
just one more question: when I use all DE genes as my geneset of
interest(around 700 genes), the top predicted ligand has a negative person,
and AUPR values are around 0.47. When I set the gene set of interest based
on the relevant enriched pathways for all DEG, I got a better person and
AUPR. I am a bit confused here. What is your saying? See the attached
pictures also on your GitHub page!!

Thank you so much for being here and answering my question!!
Best,
Amare

**Comment by browaeysrobin** [comment]
Hi @adesalegn 

I start thinking that your background set of genes is too small compared to your geneset of interest. These enrichment analyses only give good results when the geneset of interest is much smaller than the background (5-20 times smaller).

**Comment by adesalegn** [comment]
Hi ,

Thanks for the answer. I realized that allready after abit of reading
around nichenet. But the question is, is that a good approach to tackle the
problem?

Best,
Amare
