### ISSUE TITLE
Why not do differential expression directly on ligands?

### ISSUE THREAD

**Issue by meg-bit** [saeyslab/nichenetr#175]
Hi, thank you for developing this nice tool. I followed the step-by-step process to find target genes. The Nichenet process first does the analysis of differential expression on genes of the receiver. Then,  it finds the active ligands by correlating them to these differentially-expressed receiver genes. After that, it infers the target genes. 

My question is why not directly find ligands by doing differential expression on the ligand genes? Since we use ligands to infer targets anyway, isn't it better to directly identify these ligands by doing an analysis of differential expression based on a condition? And then use these genes to infer targets.

**Comment by browaeysrobin** [comment]
Hi @meg-bit 

In the standard NicheNet analysis pipeline, you will rank potential ligands based on their ligand activity (target gene enrichment). By default, the potential ligands are those ligands that are expressed by >= 1 of the sender cell types and bind a receptor expressed by the receiver. However, you can change the definition of potential ligands and only include DE/upregulated ligands if you have the data to define this. This is a very valid approach, you might just miss ligands that change in activity due to post-transcriptional mechanisms and not transcriptional ones. Another scenario that we encountered previously in one of our collaboration is that a sender cell type upregulates chemokines which then attract the receiver, and then the non-DE but very important sender-cell ligands can influence the receiver cell type. This is one reason why we don't take DE ligands as potential ligands by default. Another reason is broader usability to other datasets and questions than classic pairwise case-control data (cf our vignette / case study on pEMT programs in tumors).

If I am understanding your question correctly, you also seem to hint at is: just taking all DE ligands and use NicheNet to predict their target genes in the receiver. This is also perfectly possible. It will then just not be possible to rank/prioritize ligands based on activities. The main reason why we rank ligands by default based on activities is to prioritize ligands out of many potentially expressed and DE ligands. Another reason is that high predict ligand activity indicates that ligand might be actively involved in the cell-cell communication, and that it was expressed at the protein level instead of RNA only, and spatially close enough to have effect.

So to conclude, what you say makes sense and if you think that's better for your data, you can certainly use this. It is good to consider NicheNet as a flexible framework rather than a rigid one-solution-fits-all method. Just realize that you typically should interpret results differently if you do different things.
