### ISSUE TITLE
Background genes

### ISSUE THREAD

**Issue by nasjr08** [saeyslab/nichenetr#182]
I am slightly confused about what the background genes should be in the analysis. In this [vignette](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md):  the background genes are given as all expressed genes in the receiver population that are found in the ligand target matrix. But wouldn't it be more appropriate if the genes of interest are also removed from the background genes? Or are they required to be part of background genes for a fair comparison?

Further, is it also necessary (as is indicated in the same vignette) to intersect with the targets provided in the ligand_taget matrix? How would the analysis be affected if this is not done?

Thank you,
Naseer

**Comment by csangara** [comment]
To answer this question, I will explain how the ligand activity score calculation works.

We use two vectors to calculate the ligand activity score: 1) a vector with the length equal to the number of background genes + genes of interest, and 2) columns from the ligand-target matrix for each potential ligand. Vector 1 is binarized so that genes belonging to the gene set of interest have the value 1, and background genes have a value 0. Thus, vector 2 has to be subsetted to be the same length as vector 1 to make the metrics calculation possible (Pearson correlation, AUPR, etc.).

Hope this helps.
