### ISSUE TITLE
Opposing directionality of predicted ligand vs. predicted targets

### ISSUE THREAD

**Issue by ajwilk** [saeyslab/nichenetr#19]
Hi there,
Thanks for a fantastic tool! I'm applying NicheNet via the nichenet_seuratobj_aggregate() wrapper to a dataset with 2 conditions ("Case" and "Control"). The question I want to ask is, in a given cell type (eg. classical monocytes), what ligands from all senders could be explaining the DE genes in the "Case" CD14 Monocytes?
```
nichenet_out = nichenet_seuratobj_aggregate(
  seurat_obj = seu_combined, 
  receiver = "CD14 Monocyte", 
  condition_colname = "Status", condition_oi = "Case", condition_reference = "Control", 
  sender = "all",
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "human")
```
TGFB1 is predicted as the "top" ligand and is predicted to act through four receptors. 
![image](https://user-images.githubusercontent.com/43042369/78614904-cd7e8c80-7824-11ea-9a1c-22e4b0545312.png)
![image](https://user-images.githubusercontent.com/43042369/78615328-0a974e80-7826-11ea-9264-5471b3edbc88.png)

While all the predicted target genes are upregulated in the Cases vs. Controls, the ligand (TGFB1) and 2/4 receptors are more highly expressed by the Controls. 
![image](https://user-images.githubusercontent.com/43042369/78615507-927d5880-7826-11ea-87f0-209ccf3f8760.png)

Additionally, there is no cell type in the dataset where TGFB1 is more highly expressed in Cases than Controls. This issue persists when ```geneset = "up"``` is specified.

Any thoughts?

**Comment by browaeysrobin** [comment]
Hi @ajwilk 

The ligand prioritization is currently done without taking into account to expression value of the ligand, the only condition is that the ligand is expressed. This means that the algorithm does not consider whether a ligand is more strongly expressed in the case vs control, as long as it is expressed at a sufficient level. Of course, this might be interesting information to use for further prioritization after the NicheNet ligand activity analysis.

Changing `geneset = "up"` will make that the possible target gene set of interest will only include genes that are upregulated in the case vs control, and not all DE genes as is default.  So this has nothing to do with the ligands you select for the analysis.

Now to explain your observation, you could consider following hypothesis. Note that some ligands might downregulate many genes (instead of, or in addition to, upregulate many genes). This means that if TGFB1 is active in the control condition, it can downregulate genes there. When TGFB1 itself is repressed in the case condition, and has a lower expression, its downregulatory effect might disappear, leading to upregulation of genes that are a downregulated target gene of TGFB1.
