### ISSUE TITLE
Is the prior model/ligand-target weight matrix available for prediction using logfoldchang?

### ISSUE THREAD

**Issue by Lin13432** [saeyslab/nichenetr#191]
HI, 
In NicheNet, the differential expressed genes are marked as binary data(1 or 0) to do the correlation analysis for each ligand, I am wondering if we can use the logfoldchange of target genes like continuous data to do the correlation analysis? 
I am thinking if it would be more accurate but I am concerned about if those parameters used for building the prior model (obtained by 
mlrMBO) are still optimal for that.
If it is not allowed, could you explain the reason? Thanks in advance!

**Comment by csangara** [comment]
Hi,

We experimented with using continuous data while we were developing the package and we found that binarizing it gave much better results during model evaluation (probably because the binary data is more robust against noise). So while I wouldn't say it is 'not allowed', I wouldn't really recommend you to do it.

Hope this helps!
