### ISSUE TITLE
Difference of the prior model between version 1 and version 2

### ISSUE THREAD

**Issue by Shin8a** [saeyslab/nichenetr#211]
Hi!

Thank you for developing a great tool! NicheNet matches what I want to clarify in my project.
So, I have been using NicheNet with my snRNAseq data from mouse brain. Since the prior model has been updated recently, I just tried following [this tutorial](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md), then I realized that the result was completely different from the result using the first version of NicheNet prior model.

So, I would like to ask you
1. Could it happen? If so, is that likely due to the big difference of the prior model between version 1 and 2?
2. Actually, what is the difference of the prior model between version 1 and 2?
3. Is there anything that we should note about the version difference?

Any small help would be very appreciated!
Thank you for your time in advance.

**Comment by csangara** [comment]
Hi, thanks for using our tool! I

1. Indeed, we've observed that the resulting ligands can be very different when using the new prior model. However, we also observed that the top hits are usually from the same signaling pathway.
2. The main difference between the v1 and v2 prior model is the additional data sources that are included, which translates to an increased number of ligands in the model (688 ligands vs 1226 ligands for the human model) and additional evidence for certain interactions. Therefore, although the same ligand in v1 and v2 will have similar ligand activities, it could be ranked lower because of new ligands in the v2 model that have higher scores.
3. Because there are more ligands, we now recommend users (and we also changed the default settings of the functions) to look at the top 30 ligands instead of the top 20.

Hope this helps!

**Comment by csangara** [comment]
Unfortunately we don't really have a benchmark on this estimate, it's something we found out after running NicheNet on various use cases. The main advice we give to people is that the number of DE genes should sufficiently be lower than the number of background genes.

**Comment by Shin8a** [comment]
Understood.
Thank you so much for your kind reply!
