### ISSUE TITLE
Guide to Data Preperation

### ISSUE THREAD

**Issue by UlrichSti** [saeyslab/nichenetr#23]
Hello, is there some sort of guide or tutorial for the how the data input has to look like and the meta information which has to be given ? The tutorial file is not much help here as it is an already prepared r object.

**Comment by browaeysrobin** [comment]
No, you can be flexible with how the input data looks like. The only thing you absolutely need is a list of genes affected in your receiver cell due to intercellular communication with a sender cell (this list can be obtained in several ways, eg via DE analysis on your receiver cell data). Preferably, you also have expression data of the sender cell to reduce the list of potential ligands from all ligands in the database to only ligands expressed in the sender cell.

In this vignette https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_geneset.md we used an expression matrix, a metadata table indicating the celltype of each cell, and a list with affected genes for which we wanted to predict upstream ligands. For the vignettes dealing with seurat objects, we just used a seurat object and in the metadata we added a column indicating the cluster/celltype and condition. DE analysis to define the affected genes is done there automatically.

If you would still be in doubt about how the data should look like, you can just download the example R objects and explore in R how they look like.
