### ISSUE TITLE
how to use nichenet in cell development data

### ISSUE THREAD

**Issue by GGboy-Zzz** [saeyslab/nichenetr#239]
Hi,
I have two development stage scRNA data, and  I want to identify the improtant cell-cell interactions during the two stage. But I encounterd a problem that i cant define the sender/receiver celltypes, there have been a significant change in celltype before and after. The vignettes "differential_nichenet_pEMT.md" seems to be suitable for my data, yet it's deprecated. So, can you give me some guidance?

**Comment by GGboy-Zzz** [comment]
I ran the "differential_nichenet_pEMT.md" vignettes. An error occurred while running "get_ligand_activities_targets", which said "`receiver` must be size 18285 or 1, not 2". this is because I definded 2 receiver under one of the conditions (the 2 receiver is necessary to me), I plan to add a same condition in the "niche_geneset_list", is this aaproach correct?

**Comment by GGboy-Zzz** [comment]
@csangara I ran the "differential_nichenet_pEMT.md" vignettes hardly and solved the warnings continuously, but In the final visualization steps，It seems infeasible to define two recievers. And I have tried  "multinichenetr",  I failed because I don't have sampleid information，I wish you can generously give me some advice.

**Comment by csangara** [comment]
Hi, indeed as you have said, it's not possible to define two receiver cell types in the Differential NicheNet pipeline. This is also mentioned in the vignette. It's also partly why we deprecated it, because we wrote it for quite a specific use case where all the senders and receivers in each niche are different, and where there is only one receiver per niche.

In most cases however, it should be possible to adapt the NicheNet pipeline to your use case without using Differential NicheNet. Would you mind explaining your use case in more detail? If you are uncomfortable doing it here, you can also send us an e-mail at info[at]nichenet.be.

**Comment by GGboy-Zzz** [comment]
Thanks for your reply! Actually, my single cell data have 4 conditions, but there are some differences in cell_types under four conditions. For example, we think the receiver in condition1 is cell A, yet the receiver in condition2 is cell A and cell B, we want to infer the cell to cell interactions differences between 4 condition, basic nichenet pipeline seems to not applicable in this situation.
