### ISSUE TITLE
So much targets in nichenet_output$ligand_activity_target_heatmap after running nichenet_seuratobj_aggregate

### ISSUE THREAD

**Issue by Magetutor** [saeyslab/nichenetr#243]
Dear Csangara,

Thank you very much for developing such an excellent software. I am currently using the latest version of nichenetr to analyze my data. I found that after using the nichenet_seuratobj_aggregate function for analysis, I further used the nichenet_output$ligand_activity_target_heatmap for visualization. However, there are too many targets in my data, making it difficult to see the target heatmap clearly. I would like to ask if there is a parameter that can adjust the number of targets. If there is no corresponding parameter, how can I adjust the number of targets?

Once again, thank you for your contribution to cell-cell communication. I look forward to your reply.

Best regards,
Mage
<img width="991" alt="Snipaste_2023-12-31_19-58-59" src="https://github.com/saeyslab/nichenetr/assets/63154430/7f4ab1e4-b5a7-4c2d-b9ba-64c532fcf584">

**Comment by csangara** [comment]
Hi Mage,

Thanks for using our tool! You can adjust the number of targets with the `top_n_targets` parameter. This indicates the number of top target genes that will be considered per ligand. You can also try increasing the value of the `cutoff_visualization` because currently there is cutoff on ligand-target scores for nicer visualization.

Best regards,
Sai
