### ISSUE TITLE
Problem with get_expressed_genes()

### ISSUE THREAD

**Issue by kohtamatsuura** [saeyslab/nichenetr#27]
Hi!
Thanks for your awesome tool!

I tried to get genes expressed by more than 10% of cells by using "get_expressed_genes()". However, I felt this function returns biologically wrong expressed genes, like some macrophage markers being expressed by T cells. I guess this is caused because get_expressed_genes() looks at "SCT" assay which is based on "corrected" count matrix. (I mean some genes are changed from zero to non-zero.)
Maybe I can avoid this problem by using SCTransform() with "do.correct.umi=FALSE", but I want you to change get_expressed_genes() so that we can choose assays to look at in this function. I think this problem will be solved by using "RNA" assay.

Or, alternatively, getting expressed genes based on expression level in "SCT" assay is also great.

This problem leads to wrapper function for SeuratObject because get_expressed_genes() is also included in this wrapper function, maybe.

Thank you!

**Comment by browaeysrobin** [comment]
Hi @kohtamatsuura 

The code of `get_expressed_genes()` is adapted. Via the new paramter `assay_oi` you can select the assay you want to use to define expressed genes.

I did some comparisons on my own datasets to check the difference between using RNA and the SCT assay, and saw not much difference in the expressed genes I got. So it might be possible that you will still get some macrophage marker genes that are also expressed by your T cells (with expressed = having a non-zero value in at least 10% of T cells). If you want to avoid that you can use a more stringent cutoff instead of 10%.
