### ISSUE TITLE
Error when passing the  recorrect_umi argument in get_lfc_celltype

### ISSUE THREAD

**Issue by NeuralBind** [saeyslab/nichenetr#282]
Hey, i would like to pass the FindMarkers argument reccorect_umi= F, in the  get_lfc_celltype. But it seems to not recognize the argument. Is there maybe a workaround? 

Cheers!

**Comment by csangara** [comment]
Hi, two things you could try:
1) Check whether there was a typo in the argument (i.e., has to be `recorrect_umi = F` instead of `reccorect_umi= F`)
2) Check if you have the latest NicheNet version (v2.1.5); in older versions it was not possible to pass extra arguments to `FindMarkers`

If both of these fail, you can try copying the code of [`get_lfc_celltype`](https://github.com/saeyslab/nichenetr/blob/d8a5b5a2effc572d387769bf054a5d4a165fb37d/R/application_prediction.R#L2174) and directly give the argument to `FindMarkers`.
