### ISSUE TITLE
Protein complex

### ISSUE THREAD

**Issue by HMU-lyz** [saeyslab/nichenetr#286]
When NicheNet was modeling, did it consider the protein complex of the ligand receptor? If not, what was the reason? If it was considered, how did NicheNet calculate the expression level of the complex?

**Comment by csangara** [comment]
No, we did not consider the protein complexes. This is because we did not want to be too stringent with the filtering, i.e., requiring all subunits of the complex to be expressed. This is something that can be constrained by the user themselves of course. So when defining the potential ligands, instead of considering all expressed receptors, you could instead define the receptor as expressed only if all their subunits are expressed.
