### ISSUE TITLE
How is the Ligand-Target-Matrix generated?

### ISSUE THREAD

**Issue by Smeerlap** [saeyslab/nichenetr#293]
Dear developers, 

thanks for providing this great tool! I have used your package for a while now, but when thinking a bit more about my results, I was wondering how exactly the ligand-target-matrix is generated and how I have to read this. Specifically, a transmembranous protease (Adam17) involved in the shedding of several interesting proteins (inflammatory regulators like TNF) came up in my analysis. I have two questions for this: 

1) How do I have to read the ligand-target matrix? Does the gene in the rowname indicate the ligand and the columns the target genes (so if I filter the rownames for my ligand of interest and sort this by descending regulatory potentials, does this show me the genes that are most confidently regulated  by ligand)? Or is it the other way around, meaning the colnames indicate my ligand and the rownames show the targets? OR am I completely wrong and this table needs to be read completely differently. 

 2) Given that my ligand is a protease cleaving off other proteins, I was wondering where I can look up where the information about the downstream target activity comes from. I just have a hard time imagining how my ligand's activity (shedding) directly induces downstream signaling activity in the recipient cell. Could it be that the activity is indirectly calculated by the activity of the cleaved of proteins that then act as ligands (e.g. ADAM17 sheds TNF which then acts as the actual ligand?).

I would really appreciate your help on this to make more sense of my results. 

Thanks a lot, 

Smeerlap

**Comment by finncreeggan** [comment]
I believe here it's commented that ligands are in the columns and target genes are in the rows under the heading "Load the ligand-target model we want to use." https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_activity_single_cell.md.

**Comment by csangara** [comment]
Dag Smeerlap,

1. Finn is correct that the ligands are in the columns and target genes are in the rows. An easy way to check is by using `dim` and remembering that the one with the smaller dimension is the ligand. Indeed, if you sort by descending regulatory potential, this would show the target genes that are most likely to be regulated by that ligand based on the available evidence.

2. While the process you’re suggesting *could* be what’s happening, I would advise against drawing conclusions on the signaling mechanism based solely on the NicheNet ligand activity analysis, especially if TNF itself wasn’t ranked highly. The prior model of NicheNet, which is used to calculate the ligand activity, is created by compiling various databases, i.e., ligand-receptor, intracellular signaling, and transcription factor regulatory networks (cf. NicheNet paper, Figure 1). Our model is built based on the fact that ‘some form of’ interaction exists based on these databases, rather than detailing a precise signaling mechanism. Since ADAM17 is involved in cleaving multiple proteins, it is probably present in a lot of these databases (and therefore, is connected to many nodes in our network) even though it may not directly take part in cell-cell communication.

    All this is to say: don't overinterpret it, it could also be a spurious prediction since ADAM17 is involved in so many processes. We would normally place more importance on ligands that are known to directly participate in LR interactions.

    But, if you want to know how ADAM17 is connected to a target gene in our model, you can try the [signaling path vignette](https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md).

Hope this helps,
Chananchida
