### ISSUE TITLE
when sender cell type is only one, 

### ISSUE THREAD

**Issue by jeffchen2000** [saeyslab/nichenetr#295]
I may be wrong but, in my data, when sender cell is set to only one cell type (in your example, you used 6 cell types), the figure "LFC in sender" cannot be plotted correctly, it shows "NA" genes with LFC (I have checked, there are some genes in the sender with significant LFC though).

**Comment by csangara** [comment]
Hi,

You're indeed correct! The issue is with this line:

```
vis_ligand_lfc <- as.matrix(DE_table_top_ligands[rev(best_upstream_ligands), ])
```

You can fix this by adding a `drop=FALSE` option as follows (note the extra comma):

```
vis_ligand_lfc <- as.matrix(DE_table_top_ligands[rev(best_upstream_ligands), , drop=FALSE]) 
```

More information on this behavior is explained [here](https://adv-r.hadley.nz/subsetting.html#simplify-preserve). Thanks for pointing this out though, I will update the vignette with `drop=FALSE` so it works in all cases.
