### ISSUE TITLE
Calculate correlation scores for multiple ligands?

### ISSUE THREAD

**Issue by uberholzer** [saeyslab/nichenetr#30]
Hi,
This is not a software issue but I am wondering if there is a way to calculate a score for how the target genes of a group of ligands are enriched in a gene set of interest. My understanding from the FAQ is that the Pearson correlation is calculated for each ligand separately. I would ideally like to show that including x number of ligands produces optimal correlation between target genes and my gene set of interest. Does NicheNet have a way to do that? 
Thanks!

**Comment by browaeysrobin** [comment]
Hi @uberholzer 

You can have a look at the following vignette:
https://github.com/saeyslab/nichenetr/blob/master/vignettes/target_prediction_evaluation_geneset.md

This shows how to make a 'multi-ligand' model (random forest in this example) that will use the prior regulatory potential scores of n ligands of interest to predict the target gene set of interest (instead of looking one by one).
