### ISSUE TITLE
Cannot find the following identities in the object: Other

### ISSUE THREAD

**Issue by arunchakra** [saeyslab/nichenetr#305]
Hello I am running the standard Niche Net pipeline and following this vignette: 
https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_wrapper.md

I am getting an issue when running this portion: 
nichenet_output_agnostic <- nichenet_seuratobj_aggregate(
  seurat_obj = seuratObj, 
  sender = "G_180-315",
  receiver = "S_180-315", 
  condition_colname = "Niche",
  condition_oi = "180-315",
  condition_reference = "Other",
  expression_pct = 0.05,
  ligand_target_matrix = ligand_target_matrix,
  lr_network = lr_network,
  weighted_networks = weighted_networks
  )

[1] "The RNA assay will be used for the analysis."
[1] "Read in and process NicheNet's networks"
[1] "Define expressed ligands and receptors in receiver and sender cells"
[1] "Perform DE analysis in receiver cell"
Error in WhichCells.Seurat(object = object, idents = ident.2) : 
  Cannot find the following identities in the object: Other

The condition column, Niche has the following values 180 -315 and Other: 
> table(seuratObj$Niche)

180-315   Other 
  64154  128219 

Meanwhile the senders and recievers are in a different column that is set to the identity of the Seurat object. This should be just like the vignette so I am confused by this error. Could you please help if you have an idea?

**Comment by csangara** [comment]
Hi,

Sorry for the late reply. Have you checked if there are sender/receivers in the "Other" condition? The name of the cell types makes it seem like these cells are only present in the "180-315" condition. In this case it will not work, because the gene set of interest is determined as the DE genes between S_180-315 cells in the "180-315" condition and S_180-315 cells in the "Other" condition.

To pinpoint where the error is occuring exactly, you can also follow the [step-by-step vignette](https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md)

**Comment by sexyfoxx** [comment]
I have solved this problem.The reason is the receiver  and the sender do not esixt in condition_oi  or condition_reference
