### ISSUE TITLE
Extract target genes other than the top 20 ligands

### ISSUE THREAD

**Issue by yxiao832** [saeyslab/nichenetr#34]
Hi, 
I am using NicheNet for a single-cell RNA-seq dataset. 

Based on the FAQ, the ligands with Pearson score > 0.1 might be interesting. So I applied 0.1 as cut off and overlap these ligands with the output from CellPhoneDB. 

Now I want to pull out the targets information of a few overlapped ligands from NicheNet output, although not ranked as top 20. 

I used the command as follows:

> LigandList=c(a,b,c,d)

> active_ligand_target_links_df = LigandList %>% lapply(get_weighted_ligand_target_links,geneset = geneset_oi, ligand_target_matrix = ligand_target_matrix, n = 200) %>% bind_rows() %>% drop_na()

Then I noticed the weight for the same target genes keeps changing with the number of Ligands of interest I put here. 

For example:  the weight of Foxo3 genes would be 0 and 0 for ligand a, b respectively,  if my LigandList= c(a,b,c,d). 
but the weight of Foxo3 genes would be 0.004 and 0.001 for ligand a, b respectively, if my LigandList= c(a,b).

It seems the weight is calculated in a relative way?

Could you let me know which would be the correct way to extract the target information?

Thanks!
Yang

**Comment by browaeysrobin** [comment]
Hi @yxiao832,

Do you really observe this already in the `active_ligand_target_links_df` object? I would doubt so because with the `get_weighted_ligand_target_links()` function, weights are normally not calculated relatively. 

However, in the next step where you calculate `active_ligand_target_links` with `prepare_ligand_target_visualization` , some ligand-target links are put to zero if their weights are not higher than the defined threshold. If you use a different number of ligands as input, you get different ligand-target links with different weights, and since the threshold is relative, the threshold will be different. As a result it is possible that some ligand-target links will get a score of zero for one set of ligands, and non-zero for another set.  (This cutoff is needed for visualization and interpretation because almost all ligand-target links have non-zero scores.)

To get the most strongly predicted targets of each ligand individually, I would suggest looking at `active_ligand_target_links_df`. If you want to compare absolute ligand-target scores between different ligands, you can check  `active_ligand_target_links` (and if you don't want to use a threshold, you can change the `cutoff` parameter in that function).

**Comment by yxiao832** [comment]
Thanks for the very helpful reply! 
Yes, you are right. I didn't realize the cutoff also set some lower value to zero when I compare several ligands.
