### ISSUE TITLE
Nichenetr for proteomics data?

### ISSUE THREAD

**Issue by yankeqiang** [saeyslab/nichenetr#38]
Thank you for your package.
My project is on quantitative proteomics analysis in different cell type of a tissue. But I am not sure if this method is also suit for proteomics data set. The biggest problem is if I can use the ligand_target_matrix directly for proteomics data. 

Thanks for your help!

**Comment by browaeysrobin** [comment]
Hi @yankeqiang,

This sounds really interesting. I think conceptually NicheNet can be used on quantitative proteomics data as well.  The ligand-target matrix indicates the potential that a certain ligands regulates the expression of a certain gene. Since proteomics gives you the expression at the protein level, I think there is no problem in using NicheNet on it. I just never had done it myself.
