### ISSUE TITLE
Cannot use `expressed_genes_receiver` with `assay_oi = 'SCT'`

### ISSUE THREAD

**Issue by jaquol** [saeyslab/nichenetr#39]
I am trying to run nichenetr on a Seurat object resulting from the Seurat integration workflow. When I first try to determine which genes are expressed with:

```
expressed_genes_receiver = get_expressed_genes(receiver, seuratObj, pct = 0.10)
```

I get this warning:
```
Seurat object is result from the Seurat integration workflow. Make sure that this way of defining expressed genes is appropriate for your integrated data. The expressed genes are defined based on the integrated slot
```

My reasoning was then to use the SCT assay instead with:
```
expressed_genes_receiver = get_expressed_genes(receiver, seuratObj, pct = 0.10, assay_oi = 'SCT')
```

But then I get this error:
```
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```

I looked into the `get_expressed_genes` code and I narrowed the error to this part:
```
    if (!is.null(assay_oi)) {
        if (!assay_oi %in% Assays(seurat_obj)) {
            stop("assay_oi should be an assay of your Seurat object")
        }
    }
```

`!assay_oi %in% Assays(seurat_obj)` cannot be assessed because, I understand, a vector is expected but the output of `Assays(seurat_obj)` is a list.

My first question is whether my reasoning of forcing the use of the SCT assay is correct.

My second question is if you could please help in overcoming the issue here reported.

Thank you in advance!

Javier

**Comment by browaeysrobin** [comment]
Hi @jaquol,

I would suggest setting  `assay_oi = 'RNA'` to define expressed genes. Can you check whether this works?

**Comment by jaquol** [comment]
Hi @browaeysrobin,

Thank you for your quick reply! I am afraid that `assay_oi = 'RNA'` does not work either on my side; I get the same error as in my previous message.

**Comment by jaquol** [comment]
Hi @browaeysrobin,

I thought that I might be able to overcome the issue above by deleting the "SCT" and/or "integrated" assays. Inspired by [this](https://www.biostars.org/p/401818/), I deleted both the "SCT" and "integrated" assays with:

```
seuratObj@assays$integrated <- NULL
seuratObj@assays$SCT <- NULL
```

Unlike previously, this way I do not get any warning when running the `get_expressed_genes` function:
```
expressed_genes_receiver = get_expressed_genes(receiver, seuratObj, pct = 0.10)
```

My questions are then:

1. Does deleting the "SCT" and "integrated" assays makes sense?
2. Is "RNA" the preferred assay to run nichenetr on?

Thank you!

**Comment by browaeysrobin** [comment]
Hi @jaquol 

Deleting the SCT and integrated assays is only a temporary solution to this error of course.  
I tried to reproduce the error, but again, everything runs fine with me and I can select different assays (RNA, SCT) via the `get_expressed_genes function`.  In my case `Assays(seurat_obj)` returns a vector and not a list, in contrast to what you mentioned before. Maybe there is again an issue with a conflict with another package (as for your other issue)? 

The selection of which slot (RNA/SCT/integrated) in this `get_expressed_genes()` function will only effect which genes will be considered to be expressed (which affects the background of genes for the ligand activity analysis and the selection of ligands/receptors used as input for this). This warning that this function throws when having a SCT and/or integrated assay in addition to the RNA assay is just to let users think about whether the way `get_expressed_genes()` defines expressed genes is a correct way to do it for transformed data.  `get_expressed_genes()` will look at the fraction of cells having a non-zero expression value for a specific gene. Because data transformation could change zeroes to non-zeroes and vice versa, I would recommend using the unaffected RNA slot. But, out of experience I can say that choosing SCT / RNA / integrated does not make much difference in which genes you get out as expressed in the end. Typically, choosing RNA will result in a slightly higher number of expressed genes, but differences in number are minor (eg 5950 vs 6000 expressed genes).

**Comment by tkapello** [comment]
I started implementing the NicheNet code to my sc dataset and I wanted to report the same issue. Switching the argument to `"RNA"` does not work and, in my case, the integrated gene list is a lot smaller so I d rather use the RNA assay to have a bigger expressed gene list. If deleting the integrated slot works for some people, I would do it, but of course, an alternative would be more preferable.

Thanks in advance,
Theo

**Comment by browaeysrobin** [comment]
Hi @tkapello 

Is it possible you loaded the `SummarizedExperiment` package? If yes, could you try to run this code again without loading  `SummarizedExperiment`

**Comment by tkapello** [comment]
@browaeysrobin 

`SummarizedExperiment` seems to be needed, otherwise:

`Error in Assays(seurat_obj) : could not find function "Assays"`

**Comment by browaeysrobin** [comment]
Hi @tkapello 
Normally, `SummarizedExperiment` is not needed, because `Assays()` is also function of the Seurat package. So: did you load the Seurat package (should be yes)? 

I also was able to replicate the error you both mentioned here above if `SummarizedExperiment` was loaded after loading nichenetr/Seurat/tidyverse (because it overwrites some functions of Seurat/base R/tidyverse and loads other packages that also overwrite functions of Seurat/base R/tidyverse). However, no error was thrown when `SummarizedExperiment` was loaded before. 

So: I don't think there is an issue if you do the following

`library(nichenetr)
library(Seurat)
library(tidyverse)
seurat_obj = readRDS("data/seuratObj.rds")
expressed_genes_receiver = get_expressed_genes("celltype X", seurat_obj, pct = 0.10)
`
Here, Assays should be used from Seurat.

If you do want to load other packages, the following should work:

`library(SummarizedExperiments) # and other packages if really necessary
library(nichenetr)
library(Seurat)
library(tidyverse)
seurat_obj = readRDS("data/seuratObj.rds")
expressed_genes_receiver = get_expressed_genes("celltype X", seurat_obj, pct = 0.10)
`

**Comment by tkapello** [comment]
Hi @browaeysrobin 

I tried the order of the packages you suggested, but the error remains:
```
Error in .normarg_assays(assays) : 
  'assays' must be a SimpleList, list or array
```

Does the Seurat object need to be loaded as a .rds? I load a class Seurat object from my environment.

**Comment by browaeysrobin** [comment]
Hi @tkapello 

Could you once try this to see whether this resolves the issue?

**Comment by tkapello** [comment]
@browaeysrobin 

I tried everything you suggested and still I get the same error  :-(

```
Error in .normarg_assays(assays) : 
  'assays' must be a SimpleList, list or array
```

**Comment by browaeysrobin** [comment]
Hi @tkapello 

Could you try to
1) re-install nichenetr and run your script again ?
2) let me know whether it works now and if not: provide me with your `sessionInfo()` ?

**Comment by tkapello** [comment]
Hi @browaeysrobin 

I uninstalled and re-installed `nichenetr` and now I have the following error:

```
> # Define a receiver cell type
> receiver = "Neutrophil_0"
> expressed_genes_receiver = get_expressed_genes(receiver, baldataset, pct = 0.10, assay_oi = 'RNA')
Error: 'Assays' is not an exported object from 'namespace:Seurat'
```

As you requested, my SessionInfo():

**Comment by browaeysrobin** [comment]
Hi @tkapello 

It seems that your Seurat version is not the most recent. Could you try to reinstall the newest version?
Can you then first try to run `Seurat::Assays()` on your seurat object, and then run `get_expressed_genes()` from nichenetr again? And let me know which of these tests did work (and which not).

**Comment by tkapello** [comment]
@browaeysrobin  

you were right, it was the Seurat version. There was no `Assays` function
