### ISSUE TITLE
Negative values in PCC for ligand prediction

### ISSUE THREAD

**Issue by tkapello** [saeyslab/nichenetr#41]
This is more a question rather than an issue. I noticed in the vignettes that you use the PCC metric to rank the predicted ligands. Is there a reason why you select positive scores? Negative (but strong) correlations can be informative too.

**Comment by browaeysrobin** [comment]
Hi @tkapello 

In this section of the FAQ page I give an explanation about the interpretation of the pearson scores, also about negative scores:
https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md#how-should-i-interpret-the-pearson-correlation-values-of-the-ligand-activity-what-does-it-mean-when-i-have-negative-values

It boils down to the following: strong negative correlations in general can indeed be informative, but this situation is not likely to occur in the setting here, unless the gene set of interest and background are not properly defined. If properly defined, the gene set of interest is much smaller than the background. In that case, the pearson correlation will be positive if there is an enrichment of the higher scoring targets of a ligand in the geneset of interest compared to the background. If there is no enrichment, the correlation will be around 0. However, to get strong negative scores, yo should have an enrichment of higher scoring targets in the background, compared to the gene set of interest. This would only occur when the gene set of interest would almost entirely consist of the genes with the lowest regulatory potential scores for a ligand. And this would rarely occur by chance. 
Till now, every strong negative correlation score people reported to me, could be explained because of suboptimal settings of gene set of interest and background.
