### ISSUE TITLE
Sender/Receiver in Progenitor/Differentiated Clusters

### ISSUE THREAD

**Issue by csennis** [saeyslab/nichenetr#43]
Thank you for this wonderful package!  

I have single cell data and am working on better understanding the network between a progenitor cluster that gives rise to a more differentiated cluster.  I have performed your basic workflow using the progenitor cluster as the receiver and differentiated cluster as sender and vice versa, with differentially expressed genes as the gene set of interest.  When I compare the output of these two analyses, I get very similar receptors and prioritized ligands - is this to be expected?  Would this be evidence of bidirectional cross talk?  Or, instead, should I be limiting my analysis to one direction?

**Comment by browaeysrobin** [comment]
Hi @csennis 

If I understand you correctly, I see two possible reasons for the similarities you find:
1) Your set of potential ligands (based on expressed genes) is very similar because you used a rather loose cutoff (as default) and/or the two populations are similar
2) if you would have taken the DE genes between the two populations as 'gene set of interest', this gene set of interest would be the same for both analyses, resulting in similar top predicted upstream ligands. If you did this, I would recommend to look at only upregulated genes in one population and predict potential upstream ligands for this subset.
