### ISSUE TITLE
A question about input files

### ISSUE THREAD

**Issue by andywangcqmu** [saeyslab/nichenetr#52]
Thanks for the great package!
I have noticed that the input data in the step of "Read in the expression data of interacting cells" (https://zenodo.org/record/3531889/files/seuratObj.rds") contains data of "nGene, nUMI, orig.ident, aggregate, res.0.6, celltype, nCount_RNA, and nFeature_RNA" ,due to the limitation of the original data, I can only acquire the data of gene names and their counts, I would like to consult that if there is a way that I can still push through this process by using the incomplete data. Thank you.
Best regards.

**Comment by browaeysrobin** [comment]
Hi @andywangcqmu 

Your question is not entirely clear to me. Do you mean 1) that you only have the count matrix of your own data (and is it single-cell or bulk RNA-seq?), or 2) that you want to reproduce the analyses in the vignettes described here, but starting from the original data of the NICHE-seq study?

If you mean the first: you should of course preprocess the data yourself and define cell types of interest. After preprocessing, you can follow the basic vignette if you don't use Seurat for the processing. If you use Seurat, and you have a Seurat object of your data, you can follow one of the Seurat vignettes.

If you mean the second:  if you follow one of the Seurat vignettes, you of course need a Seurat object as input and not just the count matrix. If you want to know how we processed the original data of the NICHE-seq study into a Seurat object you can check this zenodo repository: https://zenodo.org/record/3462199.  In the directory 'application_final' > 'niche_seq', you can check the readme to know which scripts to run in which order. You can use script 1 and 3 to get the seuratObj that was submitted on Zenodo. Because this code is from more than 2 years ago and the integration /batch correction was then done via the first version of the SeuratCCA (which is not recommended anymore), it is possible that that part of the code won't work anymore. Please adapt then yourself according to the updated Seurat code and vignettes.

**Comment by andywangcqmu** [comment]
Extremely grateful for your detailed comments, I believe I have met with the second that you have mentioned, now I have solve this issue by your guidence, in the following steps of analyses, I have met with another problem and I would like to consult you again if you don't mind. In the first step of "NicheNet analysis on Seurat object", I have problem getting the "nichenet_output" when the an error is reported "the receiver should be in the metadata dataframe", I have tried numbers of names of "receiver" and "sender" including "1", "Epithelial Cells" (which are all included in the output of the seurat analysis), while the reeported error remains the same, for your information, the "seuratObj %>% Idents() %>% table()" reads as two lines,with the first line of cluster names (represented only in numbers: 1   0   3   4   5) and number of cells for each cluster. Thanks again for your kindness.

**Comment by browaeysrobin** [comment]
Hi @andywangcqmu 
I don't think the error message  "the receiver should be in the metadata dataframe" is the error message you got. Can you give the exact error message? It was probably `Your column indicating the conditions/samples of interest should be in the metadata dataframe` or `The defined receiver cell type should be an identity class of your seurat object`. If you have identified the correct error message, please read the documentation and vignette carefully to find out what you did wrong and try to solve it appropriately.
