### ISSUE TITLE
suggestions using NicheNet

### ISSUE THREAD

**Issue by yong114** [saeyslab/nichenetr#54]
Hi NicheNet team, (@browaeysrobin)

Thank you for developing such an amazing tool! I was just wondering if the NicheNet would be suitable to study the receptor interaction by comparing the cells between healthy and disease state individuals please? Very appreciated if you could give any advise on this.

Thank you very much.

**Comment by browaeysrobin** [comment]
Hi @yong114 

Could you clarify your question, because I can only give advice if I have following information.
1) Why do you need additional advice compared to information in the paper, package vignettes and FAQ? What is unclear to you?
2) Give also some more specific information about your case study, dataset, what biological questions you would like to address, what you would like to get out of the NicheNet analyses, etc.

**Comment by yong114** [comment]
Hi @browaeysrobin 

Thank you so much for your kind reply, I think I'll follow the vignettes on performing the NicheNet analysis. I have two conditions: healthy and arthritis individuals. I would like to see which ligands expressed only in certain cell types like T cell and dendritic cell when performing the NicheNet analysis. 
So would you be suggesting that I need to just follow this vignette (https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_wrapper.md) by changing the condition to "healthy" and "disease" please? In addition, I don't see any vignette on how to create a circus plot in Seurat object. I was just wondering you have any suggestion on that as well please?

Thank you again.

**Comment by browaeysrobin** [comment]
Hi @yong114 

You could indeed start using that vignette (or alternatively the vignette where the different steps are described). If you only want to focus on T-cell and DCs as 'sender cells', don't forget to indicate that in the `sender` argument of the funcion.

For tips about the circos plot by starting from a Seurat object: check https://github.com/saeyslab/nichenetr/issues/5
