### ISSUE TITLE
Heatmap visualization of top-ranked ligands and predicted regulated genes

### ISSUE THREAD

**Issue by ccp77** [saeyslab/nichenetr#55]
Hi, 

I would like to use the Heatmap visualization tool to plot the top-ranked prioritised ligands and the predicted target genes using "nichenet_output$ligand_target_heatmap" as explained in your vignettes. I have realised that sometimes some of the prioritised ligands (that can be looked at in a table using "nichenet_output$ligand_activities") are not plotted in the heatmap. This is the case for example in your vignette "Perform NicheNet analysis starting from a Seurat object" (https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_wrapper.md), where CXCL9, CXCL11 and CXCL16 are not plotted. What is the rationale behind this? Other than these few cases, it seems that the heatmap always plot the ligands ordered by pearson ranks. 
Thank you very much for your help!

![NicheNet_issue_Heatmap](https://user-images.githubusercontent.com/48820391/94824197-a6340100-03fc-11eb-92dc-22f56b0fda90.png)

**Comment by browaeysrobin** [comment]
Hi @ccp77 ,

This is probably because no gene of the geneset of interest is a strong enough target gene for these ligands. This heatmap only shows the most strongly predicted target genes and is based on some cutoffs that you can tweak. You can be more permissive to include more target genes and ligand-target links (increase value of the argument `top_n_targets` to increase the number of predicted target genes. Decreasing the value of the argument `cutoff_visualization`  could also work because currently there is cutoff on ligand-target scores for nicer visualization).

Please let me know whether playing with these values could help you out. If not, consider following the https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md vignette and check step by step after the ligand activity analysis where you 'lose' the ligands.

**Comment by ccp77** [comment]
Hi, Thanks a lot for the prompt reply. Your comments are really helpful. 
I assume that you mean changing the "n" in get_weighted_ligand_target_links, and the "cutoff" in prepare_ligand_target_visualization? 
Thank you very much again !

**Comment by browaeysrobin** [comment]
Hi @ccp77 , 
yes indeed (the arguments I mentioned where for the cases in which the seurat wrapper is used)
