### ISSUE TITLE
How to link targets with the corresponding upstream receptors expressed in receiver cells

### ISSUE THREAD

**Issue by shenyang1981** [saeyslab/nichenetr#58]
Hello, thanks for the wonderful tool. I am curious if the receptors which mediate the ligands->targets regulations can be inferred from the output. For example, I can see A -> target B, C, D and E, F, G are the receptors of A. Is it possible to infer which gene from E, F or G is the direct upstream receptor? Or maybe the actual receptor is F ( A -> F -> B), but it could be missing in the output because the original database is incomplete.

**Comment by browaeysrobin** [comment]
Hi @shenyang1981 

It is hard to discriminate which of the possible receptors are direct upstream of the target. In most cases, there will be possible upstream links between the targets and each receptors (as can be seen in https://github.com/saeyslab/nichenetr/blob/master/vignettes/ligand_target_signaling_path.md). If you still want to prioritize these receptors, you could check expression and/or cell-type specificity of these receptors. 
And you are right about potential important links missing because the prior databases are incomplete.
