### ISSUE TITLE
suggestion using Nichenet on individual clusters

### ISSUE THREAD

**Issue by rcarrr** [saeyslab/nichenetr#59]
Hi,
I would like to use nichenet on my dataset of CD45 immune clusters in a specific biological context. I don't have any conditions of interest (as healthy/diasese, untreated/treated), I want just to investigate interactions among some of these populations. I tried to define background genes as the most expressed genes in all the CD45 populations (as housekeeping genes). As gene set of interest I used genes with an high pct in my sender population. Does it make sense? Should I use marker genes of my sender population as gene set oi? Do you have any suggestion?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @rcarrr 

The first two questions of the FAQ page discuss this problem in more detail (discussion, no clear-cut answer). https://github.com/saeyslab/nichenetr/blob/master/vignettes/faq.md
You could do it as you suggest (both % approach and seurat marker approach) and find some useful results, but you should be very cautious in interpreting the results since your gene set of interest will in these cases consist of genes affected by both cell-intrinsic regulatory programs, and genes affected by the microenvironment - but you cannot distinguish between both.
