### ISSUE TITLE
Split heat maps by sender

### ISSUE THREAD

**Issue by jd10020** [saeyslab/nichenetr#66]
Dear nichenetr team,

When I was following your tutorial at the point of choosing the sender I selected more than 1 cell type and upon plotting this on a heat map I found I get a list of the top ligands but is not specifying from which cell it is coming from. I was wondering if there is a way I can split the heat map by cell type so for example if looking for ligands based on Pearson coefficient it can show me first the ligands for cell A, then the ligands from cell B and so on? I wanted something like this https://www.cell.com/immunity/pdf/S1074-7613(19)30368-1.pdf on figure 6A where ligands are separated for the different cell types (HSCs, LSECs and hepatocytes).

Thanks in advance

Diego

**Comment by browaeysrobin** [comment]
Hi @jd10020 

There are several options to do this, but they involve some 'manual' coding work. One option is to just change the ordering of the ligands to an ordering you define yourself, based on what sender cell type express ligands most strongly. In https://github.com/saeyslab/nichenetr/blob/master/vignettes/circos.md you can see an example on how to do this. 
As other option: instead of changing the ordering of ligands you show, you could make separate plots for each sender cell type.
