### ISSUE TITLE
Split results by sender populations

### ISSUE THREAD

**Issue by rcarrr** [saeyslab/nichenetr#69]
Hi!
I'm interested in the analysis of interaction regarding 5 sender populations and one receveir.
I performed my interaction analysis considering the 5 senders all together so that I have a list of ligands with a single ligand activity value.
I want now to attribute the identified ligands to the different senders. One way is to choose them based on their expression across sender population. How to choose them if their expression value is similar across senders? It could be correct to perform pairwise interaction analysis and compare ligand activities of the resulting ligands (meaning a comparison among 5 analysis)?

Thanks!

**Comment by browaeysrobin** [comment]
Hi @rcarrr 

I don't see any problem in the fact that some ligands can be attributed to more than one sender if their expression values are similar.

Doing pairwise interaction analyses will not have an influence on the ligand activities of the ligands you have now since the ligand activity only depends on the response in the receiver cell and not on the expression in the sender. But doing a pairwise analysis can help to identify some new, but lower-ranked ligands that are not in the top20 if you pool all sender cells together, but come out in the top20 ligands for one sender

**Comment by rcarrr** [comment]
Thank you!
This represents a problem for my wet colleagues who want to attribute the identified interactions to sender populations in a unique and specific way.
If I understood correctly, we can infer the strength of the interaction versus the same receveir looking at the expression of the ligands across sender populations (as explained here https://github.com/saeyslab/nichenetr/blob/master/vignettes/circos.md).
Is this correct?

**Comment by browaeysrobin** [comment]
> This represents a problem for my wet colleagues who want to attribute the identified interactions to sender populations in a unique and specific way.

Well, I think they should just accept that some ligands are expressed in a same degree by different sender populations if the data shows that it is that way

> If I understood correctly, we can infer the strength of the interaction versus the same receveir looking at the expression of the ligands across sender populations (as explained here https://github.com/saeyslab/nichenetr/blob/master/vignettes/circos.md).
Is this correct?

Indeed - note that here we have a category of ligands that are equally strongly expressed by both sender cell types
