### ISSUE TITLE
No background genes

### ISSUE THREAD

**Issue by andrebolerbarros** [saeyslab/nichenetr#7]
Hi,

I am trying to assess if the ligands of one type of cell (A) have an influence on the complete transcriptional program (both expression and inhibition of genes) of another cell type (B). Therefore, from what I understand, for this analysis, I wouldn't have a background genes set. Is it still possible to run NicheNet?

Thank you

**Comment by browaeysrobin** [comment]
Hi @andrebolerbarros 

You could use the total set of genes in the genome as the background, and the genes expressed in your cell type as gene set of interest. However, I would recommend against doing a NicheNet analysis in such a case. This because of all expressed genes, not all genes will be influenced by cell-cell interactions and most genes will be expressed because they are part of general and cell-type specific gene expression programs. If you can't discriminate between cell-intrinsic and cell-extrinsic effects in your data, and you will still use NicheNet, then ligands will be falsely linked to some 'cell-intrinsic' genes. And this will confound the analysis and lead to irrelevant and noisy predictions.
