### ISSUE TITLE
Error when I run active_ligand_target_links for single ligand

### ISSUE THREAD

**Issue by oh111** [saeyslab/nichenetr#72]
I get an error when I run the active_ligand_target_links command with a single ligand. There is no issue when there are multiple best_upstream_ligands. 

```
Error in hclust(distoi, method = "ward.D2") : 
  NA/NaN/Inf in foreign function call (arg 10)
```

**Comment by browaeysrobin** [comment]
Hi @oh111 

Do you mean the error occurs in the following command?
`active_ligand_target_links = prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, ligand_target_matrix = ligand_target_matrix, cutoff = 0.33)`

If yes, I cannot say what the reason for your error would be. The code should normally be able to handle situations with one ligand. Are you sure you only have one ligand in `active_ligand_target_links_df`? Because the hclust command that errors in your case will only run when there is more than one ligand and more than one target gene. 
To be sure, I tested this in both the basic and seurat vignette by having one upstream ligand and it works there.

If you have checked everything (have certainly a look at the content of active_ligand_target_links_df), you could maybe try re-installing nichenetr to see whether the issue is due to an older version of the package that still fails for one ligand.

**Comment by oh111** [comment]
Hi-- Thanks for the quick reply-- I will check again. I circumvented the problem by just changing the active_ligands_target_links_df such that it is in the format of a matrix for active_ligand_target_links.
