### ISSUE TITLE
Circos plot for multiple receivers

### ISSUE THREAD

**Issue by Jeff87075** [saeyslab/nichenetr#73]
Hi I'd like to ask is it possible to do a circos plot with one sender and multiple receivers? Say for example, if my hypothesis is that one cell type would interact and influence multiple other cell types, how do I integrate the results into one circos plot? Thanks a lot.

**Comment by browaeysrobin** [comment]
Hi @Jeff87075 

This is indeed possible and a good idea. We won't make a vignette for this, though.
But here is an overview of how I should do this:

The best way to do this is doing a separate NicheNet analysis per receiver, and then combining the different ligand-receptor/target tables together in one table (with indication which receptor/target from which receiver). Then you give this as input for the circlize functions similar as is explained now in the vignettes for having multiple senders and one receiver. 
One problem you might encounter is having the same receptor/targets in more than one receiver. This will give errors in the circos visualization because it can't plot same names in different sectors. To solve this, you could paste the name of the specific receiver to the receptor/target name or just paste 'empty spaces' to the receptor/target name. This latter approach is now also done in the tutorials to distinguish a gene name that can function as both ligand and receptor/target.
