### ISSUE TITLE
Making gene sets from ligand - target matrix

### ISSUE THREAD

**Issue by saeedfc** [saeyslab/nichenetr#87]
Dear,

A question regarding the database of ligand-target matrix.
Would it make sense to sort the target genes based on regulatory potential for each ligand from the 'ligand-target' matrix and select the top 20 highly regulated gene to make a 'ligand regulated gene signature'. Which we can then evaluate based on a module score using methods like Area under a recovery curve (AUCell package) or AddModuleScore function in Seurat. I came to this point because I saw that an important ligand X seemed not being there in the 'best upstream ligands'. So I tried this signature and found that some of the top 5 ligands do not have a great signature score, however, the ligand X signature score is very specific to the cluster of interest (the obvious cluster in the middle in the below figures). 

Am I completely wrong conceptually here or does it make sense to also try this in addition to the ligand prioritization method included within the nichenet package?

![image](https://user-images.githubusercontent.com/40058022/120331381-ffd32f00-c2ed-11eb-91d2-69e23c61516f.png)

![image](https://user-images.githubusercontent.com/40058022/120331840-7bcd7700-c2ee-11eb-9067-23ec5686224e.png)

**Comment by browaeysrobin** [comment]
Hi @saeedfc 

The approach you suggest makes sense conceptually. We also tried this out already and did some tests on our benchmark datasets (cf the 111 ligand-treatment datasets described in the paper). Based on that we saw that using the Pearson and AUPR measures for ligand activity were in general better than using discrete geneset-based approaches you suggest now. Of course, this was taken averaged over all datasets, so it is possible that for some datasets a geneset-based approach could work equally well or better. Also note that our benchmark was on bulk transcriptomics data, and that the optimal metrics might be different for single-cell data (at the time of working at the benchmark for the paper, there were not enough single-cell ligand-treatment datasets yet) . 

One benefit of using the geneset-based approach you suggest is interpretability, you have a very good idea of the genes you put into the geneset, so you can easily check which target genes are the reason why some cells/clusters have high signature values (in contrast to the pearson correlation used as default activity metric). 

Note 1: now you used only the top20 genes, but this might be the absolute lower end. Intuitively I would suggest to take more genes (eg top 100)

Note 2: for the default NicheNet ligand activity procedure (with pearson correlation),  it can be better to take the whole background of genes (rownames of the ligand_target_matrix) instead of only expressed genes. 

Conclusion: the approach you suggest makes sense and might be useful, but be cautious since it did not outperform the default metrics used now in our benchmark.

**Comment by saeedfc** [comment]
Great!,

Thanks a lot for the quick and detailed response!

At any point in the nichenet database building, did you also make a record of Ligand affect being positive or negative on the target genes? If I go with the geneset strategy, it would only make sense for 'upregulating' stimulus.

Kind regards,
Saeed

**Comment by browaeysrobin** [comment]
Hi @saeedfc 

Unfortunately, we did not do this because most databases we integrated did not provide this type of information.

**Comment by saeedfc** [comment]
Ok. Will keep that in mind. Thanks again!
Saeed
